version: '3'
services:
  taskmanangementapi:
    build: .
    ports:
        - '5000:5000'
    volumes:
        - ./app:/app
    networks:
      - backend
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
networks:
  backend:
    