version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  taskmanangementapi:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app
    networks:
      - backend
    depends_on:
      wait-for-db:
        condition: service_completed_successfully  
  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - mysql
    command: tcp mysql:3306 -t 30s -i 250ms
    networks:
      - backend
networks:
  backend:
    